export type ViewMode = "day" | "week" | "month";

export interface ScheduleEvent {
  id: string;
  title: string;
  type: string;
  startTime: string;
  endTime: string;
  classroom: string;
  instructor: string;
  dayOfWeek: number; // 0: Mon, 1: Tue, 2: Wed, 3: Thu, 4: Fri, 5: Sat, 6: Sun
  dateDay: number; // e.g. 15, 19, 21
  dateStr: string; // e.g. "2023-02-15"
  category: "react" | "javascript" | "html" | "cpp" | "python" | "scratch" | "olympiad";
}

export function getEventCategoryStyle(category: ScheduleEvent["category"]): {
  bg: string;
  border: string;
  text: string;
  badgeBg: string;
  badgeText: string;
} {
  switch (category) {
    case "react":
    case "scratch":
    case "olympiad":
      return {
        bg: "bg-[#e0f2fe] dark:bg-sky-950/70",
        border: "border-[#38bdf8] dark:border-sky-600",
        text: "text-slate-900 dark:text-slate-100",
        badgeBg: "bg-white/80 dark:bg-sky-900/80",
        badgeText: "text-[#0284c7] dark:text-sky-300",
      };
    case "javascript":
      return {
        bg: "bg-[#fef3c7] dark:bg-amber-950/70",
        border: "border-[#f59e0b] dark:border-amber-600",
        text: "text-slate-900 dark:text-slate-100",
        badgeBg: "bg-white/80 dark:bg-amber-900/80",
        badgeText: "text-[#d97706] dark:text-amber-300",
      };
    case "html":
      return {
        bg: "bg-[#ffedd5] dark:bg-orange-950/70",
        border: "border-[#fb923c] dark:border-orange-600",
        text: "text-slate-900 dark:text-slate-100",
        badgeBg: "bg-white/80 dark:bg-orange-900/80",
        badgeText: "text-[#ea580c] dark:text-orange-300",
      };
    case "cpp":
      return {
        bg: "bg-[#f3e8ff] dark:bg-purple-950/70",
        border: "border-[#c084fc] dark:border-purple-600",
        text: "text-slate-900 dark:text-slate-100",
        badgeBg: "bg-white/80 dark:bg-purple-900/80",
        badgeText: "text-[#9333ea] dark:text-purple-300",
      };
    case "python":
      return {
        bg: "bg-[#dcfce7] dark:bg-emerald-950/70",
        border: "border-[#4ade80] dark:border-emerald-600",
        text: "text-slate-900 dark:text-slate-100",
        badgeBg: "bg-white/80 dark:bg-emerald-900/80",
        badgeText: "text-[#16a34a] dark:text-emerald-300",
      };
    default:
      return {
        bg: "bg-slate-100 dark:bg-slate-800",
        border: "border-slate-300 dark:border-slate-700",
        text: "text-slate-900 dark:text-slate-100",
        badgeBg: "bg-white dark:bg-slate-900",
        badgeText: "text-slate-700 dark:text-slate-300",
      };
  }
}

export const MOCK_SCHEDULE_EVENTS: ScheduleEvent[] = [
  // 10:00 Slots
  {
    id: "evt-1",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 0, // Mon
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "scratch",
  },
  {
    id: "evt-1-fri",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 4, // Fri
    dateDay: 3,
    dateStr: "2023-02-03",
    category: "scratch",
  },
  {
    id: "evt-1-tue7",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 1, // Tue
    dateDay: 7,
    dateStr: "2023-02-07",
    category: "scratch",
  },
  {
    id: "evt-1-wed8",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 2, // Wed
    dateDay: 8,
    dateStr: "2023-02-08",
    category: "scratch",
  },
  {
    id: "evt-1-tue14",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 1, // Tue
    dateDay: 14,
    dateStr: "2023-02-14",
    category: "scratch",
  },
  {
    id: "evt-1-wed15",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 2, // Wed
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "scratch",
  },
  {
    id: "evt-1-wed22",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 2, // Wed
    dateDay: 22,
    dateStr: "2023-02-22",
    category: "scratch",
  },
  {
    id: "evt-1-sat25",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 5, // Sat
    dateDay: 25,
    dateStr: "2023-02-25",
    category: "scratch",
  },
  {
    id: "evt-1-sun26",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 6, // Sun
    dateDay: 26,
    dateStr: "2023-02-26",
    category: "scratch",
  },
  {
    id: "evt-1-tue28",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 1, // Tue
    dateDay: 28,
    dateStr: "2023-02-28",
    category: "scratch",
  },
  {
    id: "evt-1-wed29",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 2, // Wed
    dateDay: 29,
    dateStr: "2023-03-29",
    category: "scratch",
  },
  {
    id: "evt-1-fri31",
    title: "Scratch",
    type: "Lecture",
    startTime: "10:00",
    endTime: "11:30",
    classroom: "Class 2",
    instructor: "Zohira F",
    dayOfWeek: 4, // Fri
    dateDay: 31,
    dateStr: "2023-03-31",
    category: "scratch",
  },

  // 16:00 Slots (Monday 19 Feb & 15 Feb)
  {
    id: "evt-2",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "react",
  },
  {
    id: "evt-2-fri3",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 4,
    dateDay: 3,
    dateStr: "2023-02-03",
    category: "react",
  },
  {
    id: "evt-2-tue7",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 1,
    dateDay: 7,
    dateStr: "2023-02-07",
    category: "react",
  },
  {
    id: "evt-2-wed8",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 2,
    dateDay: 8,
    dateStr: "2023-02-08",
    category: "react",
  },
  {
    id: "evt-2-tue14",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 1,
    dateDay: 14,
    dateStr: "2023-02-14",
    category: "react",
  },
  {
    id: "evt-2-wed15",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "react",
  },
  {
    id: "evt-2-wed22",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 2,
    dateDay: 22,
    dateStr: "2023-02-22",
    category: "react",
  },
  {
    id: "evt-2-sat25",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 5,
    dateDay: 25,
    dateStr: "2023-02-25",
    category: "react",
  },
  {
    id: "evt-2-sun26",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 6,
    dateDay: 26,
    dateStr: "2023-02-26",
    category: "react",
  },
  {
    id: "evt-2-tue28",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 1,
    dateDay: 28,
    dateStr: "2023-02-28",
    category: "react",
  },
  {
    id: "evt-2-wed29",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 2,
    dateDay: 29,
    dateStr: "2023-03-29",
    category: "react",
  },
  {
    id: "evt-2-fri31",
    title: "React Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 4,
    dateDay: 31,
    dateStr: "2023-03-31",
    category: "react",
  },

  {
    id: "evt-3",
    title: "JS Level 1 Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 4",
    instructor: "Mr. Muhammadsaeed",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "javascript",
  },
  {
    id: "evt-3-15",
    title: "JS Level 1 Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 4",
    instructor: "Mr. Muhammadsaeed",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "javascript",
  },
  {
    id: "evt-4",
    title: "HTML 1 Feb Level 1",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 3",
    instructor: "Mehriddin S",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "html",
  },
  {
    id: "evt-4-15",
    title: "HTML 1 Feb Level 1",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 3",
    instructor: "Mehriddin S",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "html",
  },
  {
    id: "evt-5",
    title: "HTML 2 Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Meeting room",
    instructor: "Fariddun D",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "html",
  },
  {
    id: "evt-5-15",
    title: "HTML 2 Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Meeting room",
    instructor: "Fariddun D",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "html",
  },
  {
    id: "evt-6",
    title: "C++ Feb Level 1",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 1",
    instructor: "Zohira F",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "cpp",
  },
  {
    id: "evt-6-15",
    title: "C++ Feb Level 1",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 1",
    instructor: "Zohira F",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "cpp",
  },
  {
    id: "evt-7",
    title: "C++ 2 Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 2",
    instructor: "Mr. Kurbonali",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "cpp",
  },
  {
    id: "evt-7-15",
    title: "C++ 2 Feb",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Class 2",
    instructor: "Mr. Kurbonali",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "cpp",
  },
  {
    id: "evt-8",
    title: "Olympiad 2",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Teacher's room",
    instructor: "Omina K",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "olympiad",
  },
  {
    id: "evt-8-15",
    title: "Olympiad 2",
    type: "Lecture",
    startTime: "16:00",
    endTime: "18:00",
    classroom: "Teacher's room",
    instructor: "Omina K",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "olympiad",
  },

  // 18:00 Slots (Monday 19 Feb & 15 Feb)
  {
    id: "evt-9",
    title: "React Jan",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "react",
  },
  {
    id: "evt-9-15",
    title: "React Jan",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 6",
    instructor: "Najibullo S",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "react",
  },
  {
    id: "evt-10",
    title: "JS Pro Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 3",
    instructor: "Mr. H",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "javascript",
  },
  {
    id: "evt-10-15",
    title: "JS Pro Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 3",
    instructor: "Mr. H",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "javascript",
  },
  {
    id: "evt-11",
    title: "HTML 3 Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 8",
    instructor: "Mehriddin S",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "html",
  },
  {
    id: "evt-11-15",
    title: "HTML 3 Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 8",
    instructor: "Mehriddin S",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "html",
  },
  {
    id: "evt-12",
    title: "C# Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Meeting room",
    instructor: "Ali",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "cpp",
  },
  {
    id: "evt-12-15",
    title: "C# Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Meeting room",
    instructor: "Ali",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "cpp",
  },
  {
    id: "evt-13",
    title: "C++ Feb Level 1",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 2",
    instructor: "Muhammadsaeed",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "cpp",
  },
  {
    id: "evt-13-15",
    title: "C++ Feb Level 1",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 2",
    instructor: "Muhammadsaeed",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "cpp",
  },
  {
    id: "evt-14",
    title: ".Net Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Teacher's room",
    instructor: "Olimjon",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "cpp",
  },
  {
    id: "evt-14-15",
    title: ".Net Feb",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Teacher's room",
    instructor: "Olimjon",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "cpp",
  },
  {
    id: "evt-15",
    title: "Olympiad 1",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 1",
    instructor: "Mr. H",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "olympiad",
  },
  {
    id: "evt-15-15",
    title: "Olympiad 1",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 1",
    instructor: "Mr. H",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "olympiad",
  },
  {
    id: "evt-16",
    title: "Python Jan",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 4",
    instructor: "Mr. Odina",
    dayOfWeek: 0,
    dateDay: 19,
    dateStr: "2023-02-19",
    category: "python",
  },
  {
    id: "evt-16-15",
    title: "Python Jan",
    type: "Lecture",
    startTime: "18:00",
    endTime: "20:00",
    classroom: "Class 4",
    instructor: "Mr. Odina",
    dayOfWeek: 2,
    dateDay: 15,
    dateStr: "2023-02-15",
    category: "python",
  },
];
